language: node_js
script:
    - npm run prepublish
    - npm test
    - npm run tslint
    - npm run coverage
node_js:
  - 6
  - 4
  - "0.12"
  - "0.10"
addons:
  code_climate:
    repo_token: 5736c9c4187f1900730034ce
after_script:
  - codeclimate-test-reporter < lcov.info